// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VATMENAWebApp.Server.Data;

namespace VATMENAWebApp.Server.Migrations
{
    [DbContext(typeof(VatmenaDbContext))]
    [Migration("20210922114515_AddedPilotATCRatingTables")]
    partial class AddedPilotATCRatingTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("VATMENAWebApp.Shared.Models.Permissions.UserPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<bool>("AdminEvents")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("VATMENAWebApp.Shared.Models.VATSIM.Divisions.VatsimDivision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ParentRegion")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("SubDivisionAllowed")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VatsimDivisions");
                });

            modelBuilder.Entity("VATMENAWebApp.Shared.Models.VATSIM.MemberData.PersonalDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("VATMENAWebApp.Shared.Models.VATSIM.MemberData.VatsimMember", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Division")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("LastRatingChange")
                        .HasColumnType("datetime");

                    b.Property<int>("PilotRating")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("Reg_date")
                        .HasColumnType("datetime");

                    b.Property<string>("Region")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("SubDivision")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime?>("Susp_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("VatsimMembers");
                });

            modelBuilder.Entity("VATMENAWebApp.Shared.Models.VATSIM.Ratings.ATCRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Long")
                        .HasColumnType("text");

                    b.Property<string>("Short")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ATCRatings");
                });

            modelBuilder.Entity("VATMENAWebApp.Shared.Models.VATSIM.Ratings.PilotRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Long_name")
                        .HasColumnType("text");

                    b.Property<string>("Short_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PilotRatings");
                });

            modelBuilder.Entity("VATMENAWebApp.Shared.Models.VATSIM.Regions.VatsimRegion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Director")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VatsimRegions");
                });

            modelBuilder.Entity("VATMENAWebApp.Shared.Models.VATSIM.SubDivisions.VatsimSubDivision", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Fullname")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ParentDivision")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Code");

                    b.ToTable("VatsimSubDivisions");
                });
#pragma warning restore 612, 618
        }
    }
}
